### ISSUE TITLE
single panel please

### ISSUE THREAD

**Issue by anujgoel1** [sperez8/HivePanelExplorer#15]
Hi,
Thank you for creating a python script that can parse data for viewing as a Hive plot.
I am trying out your python script to generate Hive plot using your test friends dataset. I am interested in showing just 1 panel of hive plot instead of 4 different panels.
Also, the search text box doesnt seem to work? I have tried it on Firefox & Chrome browsers.
Many thanks for looking into it.
Kind regards,
Anuj.

**Comment by sperez8** [comment]
Hi Anuj,

I am glad you are enjoying the tool!

To make a 1x1 panel, or simply to change the axis rules of the hive plot, you need to modify the *friends_nodes_parameters.js* file in any text editor. The default 2x2 panel in the friends network is defined by these lines:

```
var columntraits = ["gender","degree"];   //node properties used to assignment nodes to axes
    rowtraits = ["height","clustering"];      //node properties used to position nodes onto axes
```

To make a 1x1 panel, or a single hive plot using say "degree" and "height" as axis rules, you could change these lines to:
```
var columntraits = ["degree"];   //node properties used to assignment nodes to axes
    rowtraits = ["height"];      //node properties used to position nodes onto axes
```
That should do it!

For the Search functionality, it works on my version of Chrome though I know I need to update it. Note that it is case sensitive so make sure you sure your search is capitalized if the node names are capitalized like in the Friends network.

Could you send me the error you get in your browser? You can see the console error by holding Ctrl-Shift-J in Chrome.

Let me know how else I can help!
Sarah

**Comment by sperez8** [comment]
I am going to close this issue since seems like all is good. Let me know otherwise.

**Comment by anujgoel1** [comment]
Thanks Sarah. Your comments helped and made a single panel.
