### ISSUE TITLE
Python 2

### ISSUE THREAD

**Issue by SilasK** [sperez8/HivePanelExplorer#16]
Hello, I like to test your cool tool but I cannot get numpy on python2.7 working.  I fear it's no longer supported. 

Do you have plans about updating the code to python3.

**Comment by sperez8** [comment]
Hi! Thanks for your interest in the tool!

I am able to run it on Python 2.7 and numpy version '1.8.0rc1'. That said, I just pushed a new version that runs on both Python 2 and 3.

Let me know if that works!
And if you use it in an academic setting, please cite the paper that was FINALLY published on the tool: https://academic.oup.com/bioinformatics/advance-article/doi/10.1093/bioinformatics/btaa683/5876826

**Comment by SilasK** [comment]
Cool, Thank you.
I think the link to the publication is not on the Github readme. It would be a good place to put it.

**Comment by sperez8** [comment]
Indeed it wasn't! Thanks for the reminder. It's there now.
If you are willing to share, I would love to see what you end up making with the tool.
