### ISSUE TITLE
gradient

### ISSUE THREAD

**Issue by har-wradim** [sperez8/HivePanelExplorer#2]
Hello Sarah,

I have also a feature request.

It would be nice to have an option to color edges with weights from continous ranges using linear gradients. For example, here is a plot for the test_*_friends.txt dataset with friendshipstrength colored applying a gradient from 0 (red) to 12 (green)

![gradient](https://cloud.githubusercontent.com/assets/2794008/4300376/cb2b54de-3e43-11e4-8510-d78ff7dc5db3.png)

**Comment by sperez8** [comment]
Hi har-wradim,

I am closing this issue since Hive Panel Explorer has overcome many problems with Hive Plotter (and does so much more!). Let me know if you ended up using this visualization you made in a publication. I would love to feature it on a page of use cases if that's okay with you.

**Comment by har-wradim** [comment]
Hi Sarah,

my congrats with the progress you are making!
Yes, sure, here is our publication: [Characterization of fossilized relatives of the White Spot Syndrome Virus in genomes of decapod crustaceans](http://www.biomedcentral.com/1471-2148/15/142).

**Comment by sperez8** [comment]
Fantastic figure! Glad it came in handy ;)

Sarah


----------------------------------------------
Sarah Perez, M.Sc.
604-842-6751
*science, communication, education*
http://munchaholic.wordpress.com/
http://canadiancamel.wordpress.com/
https://github.com/sperez8/
